{% set name = "umongo" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Scille/umongo/archive/refs/tags/{{ version }}.tar.gz
  sha256: de260478e157cba3ea8a865054fbbf76aee74da03f414d2f509cc0992c19823a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - marshmallow >=3.10.0
    - pymongo >=3.7.0

test:
  imports:
    - umongo

about:
  home: https://mdolab-pyoptsparse.readthedocs-hosted.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: sync/async MongoDB ODM, yes.
  description: |
    Î¼Mongo is a Python MongoDB ODM. It inception comes from two needs: the lack 
    of async ODM and the difficulty to do document (un)serialization with 
    existing ODMs.
  doc_url: https://umongo.readthedocs.io/
  dev_url: https://github.com/Scille/umongo

extra:
  recipe-maintainers:
    - whophil
    - lafrech
